services:
  foxglove:
    build:
      context: ..
      dockerfile: docker/vis_tools/foxglove.Dockerfile
      cache_from:
        - "${INFRASTRUCTURE_FOXGLOVE_IMAGE:?}:${TAG}"
        - "${INFRASTRUCTURE_FOXGLOVE_IMAGE:?}:main"
      args:
        BASE_IMAGE: ${BASE_IMAGE_OVERRIDE-}
    image: "${INFRASTRUCTURE_FOXGLOVE_IMAGE:?}:${TAG}"
    profiles: [deploy, develop]
    command: ["ros2", "launch", "foxglove_bridge", "foxglove_bridge_launch.xml", "port:=8080"]
    environment:
      - port=8080
      - FOXGLOVE_BRIDGE_PORT=8080
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
